"""
ODVS HF Hub Simulator — Simulates Hugging Face Hub dataset workflows.

Provides a Hub-like API surface for:
- Dataset card generation (README.md)
- Dataset preview (first N rows)
- Dataset metadata (YAML front-matter)
- Download URL simulation
- Dataset search by tag
- Dataset card rendering

This module does NOT connect to the real HF Hub — it simulates the
Hub's behavior over the local ODVS registry and Iceberg tables.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

import pandas as pd
import yaml

from odvs.logger import get_logger
from odvs.registry.dataset_registry import DatasetRegistry

logger = get_logger(__name__)


@dataclass
class HFDatasetCard:
    """Represents a Hugging Face-style Dataset Card."""
    dataset_name: str
    description: str
    tags: List[str]
    language: Optional[str]
    license: str
    version: str
    row_count: int
    column_count: int
    schema: Dict[str, str]
    source_uri: str
    created_at: str
    updated_at: str
    sample_rows: Optional[List[Dict[str, Any]]]

    def to_markdown(self) -> str:
        """Render a HF Hub-style dataset card as Markdown."""
        front_matter = {
            "license": self.license,
            "tags": self.tags,
            "language": [self.language] if self.language else [],
            "dataset_info": {
                "name": self.dataset_name,
                "version": self.version,
                "splits": {
                    "train": {"num_rows": self.row_count}
                },
                "features": {
                    col: {"dtype": dtype, "_type": "Value"}
                    for col, dtype in self.schema.items()
                },
            },
        }

        yaml_block = yaml.dump(front_matter, default_flow_style=False, allow_unicode=True)

        sample_table = ""
        if self.sample_rows:
            cols = list(self.sample_rows[0].keys())
            header = "| " + " | ".join(cols) + " |"
            separator = "| " + " | ".join("---" for _ in cols) + " |"
            rows = "\n".join(
                "| " + " | ".join(str(row.get(c, "")) for c in cols) + " |"
                for row in self.sample_rows[:5]
            )
            sample_table = f"\n## Dataset Preview\n\n{header}\n{separator}\n{rows}\n"

        schema_table = "\n".join(
            f"| `{col}` | `{dtype}` |"
            for col, dtype in self.schema.items()
        )

        return f"""---
{yaml_block}---

# {self.dataset_name}

{self.description}

## Dataset Summary

| Property | Value |
|----------|-------|
| Version | `{self.version}` |
| Rows | `{self.row_count:,}` |
| Columns | `{self.column_count}` |
| License | `{self.license}` |
| Created | `{self.created_at[:10]}` |
| Updated | `{self.updated_at[:10]}` |

## Dataset Schema

| Column | Type |
|--------|------|
{schema_table}
{sample_table}

## Source

```
{self.source_uri}
```

## Citation

```bibtex
@dataset{{{self.dataset_name.replace("-", "_")},
  title = {{{self.dataset_name}}},
  year = {{{datetime.now(timezone.utc).year}}},
  publisher = {{ODVS}},
  note = {{Version {self.version}}}
}}
```

---
*Generated by ODVS (Open Dataset Versioning System)*
"""


class HFSimulator:
    """
    Simulates the Hugging Face Hub API surface over ODVS datasets.

    Methods mirror the HF `datasets` library's Hub API:
    - list_datasets()
    - dataset_info()
    - load_dataset() (returns pandas)
    - push_to_hub() simulation
    """

    def __init__(
        self,
        registry: Optional[DatasetRegistry] = None,
    ) -> None:
        self._registry = registry or DatasetRegistry()


    def list_datasets(
        self,
        search: str = "",
        tags: Optional[List[str]] = None,
        limit: int = 100,
    ) -> List[Dict[str, Any]]:
        """
        List datasets. Mirrors huggingface_hub.list_datasets() signature.
        """
        results = self._registry.search(query=search, tags=tags)
        return [self._format_hub_entry(ds) for ds in results[:limit]]

    def dataset_info(self, dataset_name: str) -> Dict[str, Any]:
        """Return dataset metadata. Mirrors huggingface_hub.dataset_info()."""
        ds = self._registry.get_dataset(dataset_name)
        return self._format_hub_entry(ds)

    def generate_dataset_card(
        self,
        dataset_name: str,
        sample_df: Optional[pd.DataFrame] = None,
        language: Optional[str] = None,
        license: str = "apache-2.0",
    ) -> HFDatasetCard:
        """Generate a Hugging Face-style dataset card for the given dataset."""
        ds = self._registry.get_dataset(dataset_name)
        latest_version = self._registry.get_latest_version(dataset_name)

        sample_rows = None
        if sample_df is not None and len(sample_df) > 0:
            sample_rows = sample_df.head(5).to_dict(orient="records")

        row_count = latest_version["row_count"] if latest_version else 0
        schema = ds.get("schema", {})

        return HFDatasetCard(
            dataset_name=dataset_name,
            description=ds.get("description", f"Dataset managed by ODVS: {dataset_name}"),
            tags=ds.get("tags", []),
            language=language,
            license=license,
            version=ds.get("latest_version") or "0.0.0",
            row_count=row_count,
            column_count=len(schema),
            schema=schema,
            source_uri=ds.get("source_uri", ""),
            created_at=ds.get("created_at", ""),
            updated_at=ds.get("updated_at", ""),
            sample_rows=sample_rows,
        )

    def push_to_hub_simulation(
        self,
        dataset_name: str,
        df: pd.DataFrame,
        version_tag: str,
        commit_message: str = "",
    ) -> Dict[str, Any]:
        """
        Simulate pushing a dataset to Hugging Face Hub.
        Records a version in the registry and returns a simulated push result.
        """
        schema = {col: str(dtype) for col, dtype in df.dtypes.items()}

        self._registry.register(
            name=dataset_name,
            schema=schema,
        )

        import hashlib
        checksum = hashlib.sha256(df.to_csv(index=False).encode()).hexdigest()[:16]

        version = self._registry.add_version(
            dataset_name=dataset_name,
            version_tag=version_tag,
            row_count=len(df),
            checksum=checksum,
            schema=schema,
        )

        result = {
            "status": "success",
            "dataset_name": dataset_name,
            "version_tag": version_tag,
            "commit_message": commit_message or f"Upload {dataset_name} {version_tag}",
            "commit_hash": checksum,
            "row_count": len(df),
            "hub_url": f"https://huggingface.co/datasets/odvs-sim/{dataset_name}",
            "timestamp": datetime.now(timezone.utc).isoformat(),
        }

        logger.info(
            f"HF Hub simulation: pushed {dataset_name}@{version_tag} ({len(df):,} rows)"
        )
        return result

    def get_download_url(self, dataset_name: str, version_tag: Optional[str] = None) -> str:
        """Return a simulated download URL for a dataset version."""
        ds = self._registry.get_dataset(dataset_name)
        tag = version_tag or ds.get("latest_version", "latest")
        return f"https://huggingface.co/datasets/odvs-sim/{dataset_name}/resolve/{tag}/data.parquet"


    def _format_hub_entry(self, ds: Dict[str, Any]) -> Dict[str, Any]:
        latest = ds.get("latest_version")
        version_count = len(ds.get("versions", []))
        latest_rows = 0
        if ds.get("versions"):
            latest_rows = ds["versions"][-1].get("row_count", 0)

        return {
            "id": f"odvs-sim/{ds['name']}",
            "name": ds["name"],
            "description": ds.get("description", ""),
            "tags": ds.get("tags", []),
            "lastModified": ds.get("updated_at", ""),
            "createdAt": ds.get("created_at", ""),
            "downloads": 0,  # Simulated
            "likes": 0,
            "private": False,
            "gated": False,
            "version": latest,
            "numVersions": version_count,
            "numRows": latest_rows,
            "schema": ds.get("schema", {}),
        }